Repository ishanvyas22/cakephp-inertiajs, pull requests merged in 2020-11, with the labels that each got.

#12 Fast approach on a 4.x upgrade
  .travis.yml
  composer.json
  phpunit.xml.dist
  src/Controller/InertiaResponseTrait.php
  src/Middleware/InertiaMiddleware.php
  src/Plugin.php
  src/Utility/Message.php
  src/View/BaseViewTrait.php
  src/View/Helper/InertiaHelper.php
  src/View/InertiaJsonView.php
  src/View/InertiaWebView.php
  templates/Inertia/app.php
  tests/TestCase/Controller/UsersControllerTest.php
  tests/TestCase/PluginTest.php
  tests/TestCase/View/Helper/InertiaHelperTest.php
  tests/TestCase/View/InertiaJsonViewTest.php
  tests/TestCase/View/InertiaWebViewTest.php
  tests/bootstrap.php
  tests/test_app/config/routes.php
  tests/test_app/src/Application.php
  tests/test_app/src/Controller/AppController.php
  tests/test_app/src/Controller/ErrorController.php
  tests/test_app/src/Controller/UsersController.php
  tests/test_app/templates/Error/error400.php
  tests/test_app/templates/Error/error500.php
  tests/test_app/templates/layout/default.php
Labels: enhancement

#14 Fix example code
  docs/ServerSideSetup.md
Labels: bug, documentation

#13 Add more types & clarify docs
  docs/ClientSideSetup.md
  docs/Installation.md
  src/Controller/InertiaResponseTrait.php
  src/View/BaseViewTrait.php
  src/View/Helper/InertiaHelper.php
Labels: documentation, enhancement

#15 Improve docs
  docs/ClientSideSetup.md
  docs/Installation.md
Labels: documentation, enhancement

#16 Fix example code
  docs/ServerSideSetup.md
Labels: Cake3, bug, documentation
